{"name": "Test login attempt with wrong credentials", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestLogin' object has no attribute '__qualname__'", "trace": "self = <src.tests.test_selenium.TestLogin object at 0x000002ED5143BC50>\nlogin_data = ('Alexander_Artemov', 'test')\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"8bc7806704770e4cc6e771f972066604\")>\n\n    @allure.step\n    @allure.tag('UI')\n    @allure.feature('User management')\n    @allure.story('Login')\n    @allure.title(\"Test login attempt with wrong credentials\")\n    @allure.severity(allure.severity_level.NORMAL)\n    @pytest.mark.parametrize(\"login_data\", [(\"alex_art\", \"test\"),\n                                            (\"alex_art\", \"\"),\n                                            (\"\", \"\"),\n                                            (\"Alexander_Artemov\", \"test\")])\n    def test_login_incorrect(self, login_data, driver):\n        login_page = LoginPage(driver)\n        login_page.go(\"http://jira.hillel.it:8080/\")\n        login_page.login(*login_data)\n    \n>       allure.attach(self.__qualname__ + 'screenshot', self.driver.get_screenshot_as_png(), type=AttachmentType.PNG)\nE       AttributeError: 'TestLogin' object has no attribute '__qualname__'\n\nsrc\\tests\\test_selenium.py:61: AttributeError"}, "steps": [{"name": "test_login_incorrect", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestLogin' object has no attribute '__qualname__'\n", "trace": "  File \"c:\\users\\aartemov\\pycharmprojects\\pythoncourse\\phase4\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 141, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\aartemov\\PycharmProjects\\pythoncourse\\phase5\\src\\tests\\test_selenium.py\", line 61, in test_login_incorrect\n    allure.attach(self.__qualname__ + 'screenshot', self.driver.get_screenshot_as_png(), type=AttachmentType.PNG)\n"}, "parameters": [{"name": "login_data", "value": "('Alexander_Artemov', 'test')"}, {"name": "driver", "value": "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"8bc7806704770e4cc6e771f972066604\")>"}], "start": 1537453238008, "stop": 1537453254027}], "parameters": [{"name": "login_data", "value": "('Alexander_Artemov', 'test')"}], "start": 1537453238008, "stop": 1537453254028, "uuid": "7da51e4b-285c-4795-a7bc-97089ad048bc", "historyId": "384da9776e08e2dbe65b4e7101c5fe29", "fullName": "src.tests.test_selenium.TestLogin#test_login_incorrect[login_data3]", "labels": [{"name": "story", "value": "Login"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "User management"}, {"name": "tag", "value": "UI"}, {"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_selenium"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "odp1210013"}, {"name": "thread", "value": "22744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_selenium"}]}