{"name": "Test login attempt with wrong credentials", "status": "passed", "parameters": [{"name": "login_data", "value": "('alex_art', 'test')"}], "start": 1537445323417, "stop": 1537445349605, "uuid": "cf9bc894-970d-4f51-99fa-7326a2a94c1c", "historyId": "eb21a96018a81d1b7c1af44bc9928f0c", "fullName": "src.tests.test_selenium.TestLogin#test_login_incorrect[login_data0]", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User management"}, {"name": "story", "value": "Login"}, {"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_selenium"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "odp1210013"}, {"name": "thread", "value": "14380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_selenium"}]}